language: python
python:
  - "3.6"
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-server-dev-10
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
cache: pip
script:
  - pytest
notifications:
  email:
    on_success: never
    on_failure: never
