language: python
python:
  - "3.6"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
cache: pip
script:
  - pytest
notifications:
  email:
    on_success: never
    on_failure: never
